version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: impulse_auth_db
  redis:
    image: redis
    ports:
      - "6380:6379"
    restart: always